# LEARN NUMPY LIBRARY

NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. It provides a lot of supporting functions that make working with ndarray very easy. NumPy is usually imported under the np alias and are mutable.

A numpy array is similar to a list. The only difference is that a list can have items of different data types whereas a numpy array has elements of same data type only and the array object in NumPy is called **ndarray**.

We can cast a list to a numpy array by first importing `numpy`.


In [69]:
import numpy as np                                  # import numpy library

In [70]:
print(np.__version__)                               # Checking version of numpy

1.20.3


**Same functions can be used for manipulating multidimensional arrays.**

### Creating numpy arrays  

In [71]:
array=np.array([1,2,3,4,5,6,7])                     # create numpy array using list 
array

array([1, 2, 3, 4, 5, 6, 7])

In [72]:
zero=np.zeros(5)                                    # create array of zeroes (size) 
zero                                                # float values by default

array([0., 0., 0., 0., 0.])

In [73]:
np.ones(5, dtype='int32')                           # create array of ones (size) by using dtype to specify the type of elements

array([1, 1, 1, 1, 1])

In [127]:
a=np.arange(1, 7)                                   # create array from 0 or specified value to size-1 
a                                                   # much like a range function  

array([1, 2, 3, 4, 5, 6])

Linspace returns evenly spaced numbers over a specified interval.<br>**numpy.linspace(start, stop, num = int value)**
<br>start  :  start of interval range
<br>stop   :  end of interval range
<br>num    :  Number of samples to generate.

In [75]:
# Make a numpy array within [0, 2π] and 100 elements 
np.linspace(0, 2*np.pi, num=9)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714, 6.28318531])

In [76]:
# Makeup a numpy array within [-2, 2] and 5 elements
np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

### Gathering basic info of numpy array

In [77]:
print(type(a) ,'\n', a.dtype)                                        # Check the type of a and the type of the values stored
print('Size:',a.size,  '\nDim: ', a.ndim, '\nShape:', a.shape)       # Get the size, dimensions and shape of numpy array

<class 'numpy.ndarray'> 
 int32
Size: 6 
Dim:  1 
Shape: (6,)




We can modify elements and assign first 4 elements to a new numpy array using slicing.

In [128]:
a[3:5] = 300, 400                                  # Set the fourth element and fifth element to 300 and 400
d= a[2:6]
d

array([  3, 300, 400,   6])

In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])             # Slicing with steps
print(arr[1:5:2])

print(arr[1:5:])                                  # If we don't pass step its considered 1

[2 4]
[2 3 4 5]


### Basic Functions

In [129]:
np.sort(a)                                        # Sort an array

array([  1,   2,   3,   6, 300, 400])

In [130]:
np.flip(a)                                        # use axis=0 for coloum-wise flip and axis=1 for row-wise flip on 2-D arrays

array([  6, 400, 300,   3,   2,   1])

In [110]:
arr1=np.array([2,34,5])                      
arr2=np.array([1,2])
np.concatenate((arr1,arr2))                       # to concatenate two arrays of same dimensions

array([ 2, 34,  5,  1,  2])

In [111]:
arr1.reshape((3,1))                               # or np.reshape(arr1,(4,1)) ; to reshape the array into new shape

array([[ 2],
       [34],
       [ 5]])

In [112]:
# to convert an array from shape(6,) to (6,1), that is to add a new dimension,
arr1=a[np.newaxis, : ]
arr1

array([[ 1, -1,  1, -1]])

In [119]:
b=np.array([2,3,5,1,4,2,3])                      #to print all unique numbers
unique_values= np.unique(b)
unique_values

array([1, 2, 3, 4, 5])

In [124]:
unique_values, unique_indices = np.unique(b, return_index=True)        #return indices of first found unique element
unique_indices

array([3, 0, 1, 4, 2], dtype=int64)

In [125]:
np.unique(b, return_counts=True)                  #return occurances of element 

(array([1, 2, 3, 4, 5]), array([1, 2, 2, 1, 1], dtype=int64))

### Numpy Statistical Functions


In [90]:
a = np.array([1, -1, 1, -1])                      # Create a numpy array

In [91]:
mean = a.mean()                                   # Get the mean of numpy array
mean

0.0

In [92]:
standard_deviation= a.std()                       # Get the standard deviation of numpy array
standard_deviation

1.0

In [93]:
a.max(), a.min(), a.sum()                         # Maximum and minimum values

(1, -1, 0)

### Numpy Array Operations

In [94]:
u = np.array([3, 4])
u

array([3, 4])

In [95]:
v = np.array([2, 1])
v

array([2, 1])

In [96]:
np.add(u, v)             # or u+v                        # Addition; similarly add a scalar

array([5, 5])

In [97]:
np.subtract(u,v)         # or u-v                        # Subtraction      

array([1, 3])

In [98]:
np.multiply(u,v)         # or u*v                        # Multiplication (element-wise)

array([6, 4])

In [99]:
np.divide(u, v)          # or u/v                        #Division

array([1.5, 4. ])

In [100]:
np.multiply(u,2)        # or u*2                         # multiplication by scalar

array([6, 8])

In [101]:
np.multiply(u,2)        # or u/2                         # division by scalar

array([6, 8])

In [131]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [134]:
np.dot(X, Y)                                            # Calculate the dot product

7

In [104]:
# Add the constant to array
u + 1

array([4, 5])

In [135]:
np.square(u)

array([ 9, 16], dtype=int32)

### Mathematical Functions


In [66]:
# The value of pi
np.pi

3.141592653589793

In [67]:
# Create the numpy array in radians
x = np.array([0, np.pi/2 , np.pi])

In [68]:
# Calculate the sin of each elements
np.sin(x)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [136]:
np.meshgrid(X, Y)

[array([[1, 2],
        [1, 2]]),
 array([[3, 3],
        [2, 2]])]